#ifndef LONCONFIG_H
#define LONCONFIG_H


#define PHY_CLK_PIN_LIST {CLK_0_Pin,CLK_1_Pin,CLK_2_Pin,CLK_3_Pin,CLK_4_Pin,CLK_5_Pin,CLK_6_Pin,CLK_7_Pin}
#define PHY_DATA_PIN_LIST {DATA_0_Pin, DATA_1_Pin, DATA_2_Pin, DATA_3_Pin, DATA_4_Pin, DATA_5_Pin, DATA_6_Pin, DATA_7_Pin}
#define PHY_CLK_PORT_LIST {CLK_0_GPIO_Port,CLK_1_GPIO_Port,CLK_2_GPIO_Port,CLK_3_GPIO_Port,CLK_4_GPIO_Port,CLK_5_GPIO_Port,CLK_6_GPIO_Port,CLK_7_GPIO_Port}
#define PHY_DATA_PORT_LIST {DATA_0_GPIO_Port,DATA_1_GPIO_Port,DATA_2_GPIO_Port,DATA_3_GPIO_Port,DATA_4_GPIO_Port,DATA_5_GPIO_Port,DATA_6_GPIO_Port,DATA_7_GPIO_Port}


#define LON_INTERFACE_FREQ 500

#define USE_VIRTUAL_CHANNELS 0
#define USE_SENSORS 0
#define USE_SENSORS_DATABASE 0
#define USE_HTTP_INTERFACE 0
#define USE_TIMERS 0
#define USE_COMMAND_LINK 1
#define USE_EXTERNAL_LINK 0

#define USE_FILESYSTEM 0

#define NO_OF_BASIC_CHANNELS 4
#define NO_OF_VIRTUAL_CHANNELS 0

#define NO_OF_DEV_IN_CHANNEL 64


#define CHECK_DEV_INTERVAL 2
#define CHECK_ONCE_DEV_INTERVAL 30


#define CONFIG_FLASH_A  0x08020000
#define CONFIG_FLASH_B  0x08040000

#define CONFIG_FLASH_A_SIZE 0x00010000
#define CONFIG_FLASH_B_SIZE 0x00010000

#define CONFIG_FLASH_A_SECTOR FLASH_SECTOR_5
#define CONFIG_FLASH_B_SECTOR FLASH_SECTOR_6

#define CONFIG_FLASH_TIM 0x08060000
#define CONFIG_FLASH_TIM_SIZE 0x00010000
#define CONFIG_FLASH_TIM_SECTOR FLASH_SECTOR_7



#endif